/**
 * Frozen acceptance for the first-outcome summarize utility.
 * Do not edit this file to make the assignment pass — implement lib/summarize-checks.cjs.
 */
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const cli = path.join(root, 'summarize-checks.mjs');

function run(input) {
  return spawnSync(process.execPath, [cli], {
    cwd: root,
    encoding: 'utf8',
    input: typeof input === 'string' ? input : JSON.stringify(input),
  });
}

function assertSuccess(result, expectedStdout) {
  assert.equal(result.status, 0, result.stderr || 'expected exit 0');
  assert.equal(result.stdout, expectedStdout);
}

function assertFailure(result, pattern) {
  assert.notEqual(result.status, 0, 'expected non-zero exit');
  assert.match(`${result.stderr}\n${result.stdout}`, pattern);
}

// Empty input: zero counts and an empty failures list.
assertSuccess(
  run([]),
  ['passed: 0', 'failed: 0', 'skipped: 0', 'failures:', ''].join('\n'),
);

// Mixed statuses: count each and list failure names in order.
assertSuccess(
  run([
    { name: 'lint', status: 'passed' },
    { name: 'unit', status: 'failed' },
    { name: 'docs', status: 'skipped' },
    { name: 'typecheck', status: 'failed' },
  ]),
  [
    'passed: 1',
    'failed: 2',
    'skipped: 1',
    'failures:',
    '- unit',
    '- typecheck',
    '',
  ].join('\n'),
);

// Invalid JSON.
assertFailure(run('{'), /invalid JSON/i);

// Unknown status.
assertFailure(
  run([{ name: 'lint', status: 'flaky' }]),
  /unknown status/i,
);

// Missing name.
assertFailure(
  run([{ status: 'passed' }]),
  /name/i,
);

process.stdout.write('first-outcome acceptance passed\n');
